batch_size: 128
hid_dim: 256
lr: 0.002
wd: !!float 1e-4
n_layers: 2
dropout: [0.2, 0.1]
device: "cuda:6"
early_stopping: 15
n_fold: 5
seed: 2023
max_epochs: 17
gated: True
dataset: S-FFSD #amazon #S-FFSD
test_size: 0.4