dataset: amazon # yelp, amazon

batch_size: 1024 # 'Batch size 2048 for yelp, 256 for amazon.'
lr: 0.004
weight_decay: 0.00005
emb_size: 64 # Node embedding size at the last layer
num_epochs: 2000
weight: 0.6 #Epoch interval to run test set
layers: 7 # Number of layers
test_size: 0.6
val_size: 0.5
device: "cuda:7"
layers_tree: 7
seed: 22
drop_rate: 0.3


# dataset: yelp # yelp, amazon

# batch_size: 2048 # 'Batch size 2048 for yelp, 256 for amazon.'
# lr: 0.005
# weight_decay: 0.00005
# emb_size: 64 # Node embedding size at the last layer
# num_epochs: 2000
# weight: 0.6 #Epoch interval to run test set
# layers: 7 # Number of layers
# test_size: 0.6
# val_size: 0.5
# device: "cuda:1"
# layers_tree: 2
# seed: 76
# drop_rate: 0.3
