dataset: S-FFSD

trainfeature: data/trf.npy
trainlabel: data/trl.npy
testfeature: data/tef.npy
testlabel: data/tel.npy

test_size: 0.2

epochs: 30
batch_size: 64
attention_hidden_dim: 150
lr: 0.002
device: cuda:0