dataset: S-FFSD

trainfeature: data/trf_3d.npy
trainlabel: data/trl_3d.npy
testfeature: data/tef_3d.npy
testlabel: data/tel_3d.npy

test_size: 0.2

epochs: 30
batch_size: 64
attention_hidden_dim: 150
lr: 0.002
device: cuda:0